"""Coverage report for ka_GE.csv. Writes docs/coverage-report.md."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path("/home/nika/module-language-pack-ka-ge")
CSV_PATH = REPO_ROOT / "ka_GE.csv"
OUT_MD = REPO_ROOT / "docs" / "coverage-report.md"

P1_MODULES: frozenset[str] = frozenset({
    "Magento_Catalog",
    "Magento_Checkout",
    "Magento_Customer",
    "Magento_Sales",
    "Magento_Theme",
    "Magento_Email",
    "Magento_Wishlist",
    "Magento_Newsletter",
    "Magento_Review",
    "Magento_Page",
    "Magento_Cms",
    "Magento_Search",
    "Magento_Bundle",
    "Magento_ConfigurableProduct",
    "Magento_Downloadable",
    "Magento_Directory",
    "Magento_GiftMessage",
    "Magento_GiftCard",
    "Magento_GiftWrapping",
    "Magento_GiftRegistry",
    "Magento_GiftCardAccount",
    "Magento_ProductAlert",
    "Magento_ProductVideo",
    "Magento_Captcha",
    "Magento_Cookie",
    "Magento_MultishippingFront",
    "Magento_OfflineShipping",
    "Magento_OfflinePayments",
    "Magento_Persistent",
    "Magento_Quote",
    "Magento_RelatedProductGraphQl",
    "Magento_ReviewGraphQl",
    "Magento_SearchStorefront",
    "Magento_Shipping",
    "Magento_Sitemap",
    "Magento_Store",
    "Magento_Swatches",
    "Magento_Tax",
    "Magento_TaxImportExport",
    "Magento_UrlRewrite",
    "Magento_Variable",
    "Magento_Vault",
})


def main() -> int:
    totals: dict[str, int] = defaultdict(int)
    translated: dict[str, int] = defaultdict(int)
    grand_total = 0
    grand_translated = 0

    with CSV_PATH.open(encoding="utf-8", newline="") as fh:
        reader = csv.reader(fh)
        for row in reader:
            if len(row) < 4:
                continue
            module = row[3]
            totals[module] += 1
            grand_total += 1
            if row[1] and row[1] != row[0]:
                translated[module] += 1
                grand_translated += 1

    overall_pct = 100.0 * grand_translated / max(grand_total, 1)

    p1_present = sorted(m for m in totals.keys() if m in P1_MODULES)
    p1_total = sum(totals[m] for m in p1_present)
    p1_translated = sum(translated[m] for m in p1_present)
    p1_pct = 100.0 * p1_translated / max(p1_total, 1)

    # All modules sorted by pct ascending (worst at top), tie-break by total desc
    rows_all: list[tuple[str, int, int, float]] = []
    for module, tot in totals.items():
        tx = translated[module]
        pct = 100.0 * tx / max(tot, 1)
        rows_all.append((module, tot, tx, pct))
    rows_all.sort(key=lambda r: (r[3], -r[1]))

    lines: list[str] = []
    lines.append("# ka_GE Coverage Report")
    lines.append("")
    lines.append("Auto-generated by `_dev/coverage.py`. Do not hand-edit.")
    lines.append("")
    lines.append("## Overall")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Total rows | {grand_total} |")
    lines.append(f"| Translated rows | {grand_translated} |")
    lines.append(f"| Coverage | {overall_pct:.2f}% |")
    lines.append("")

    lines.append("## P1 storefront-visible modules")
    lines.append("")
    lines.append(f"Combined: {p1_translated} / {p1_total} ({p1_pct:.2f}%)")
    lines.append("")
    lines.append("| Module | Total | Translated | Coverage |")
    lines.append("|---|---:|---:|---:|")
    p1_table = sorted(
        [(m, totals[m], translated[m]) for m in p1_present],
        key=lambda r: (100.0 * r[2] / max(r[1], 1)),
    )
    for module, tot, tx in p1_table:
        pct = 100.0 * tx / max(tot, 1)
        lines.append(f"| {module} | {tot} | {tx} | {pct:.2f}% |")
    lines.append("")

    lines.append("## All modules (sorted worst -> best)")
    lines.append("")
    lines.append("| Module | Total | Translated | Coverage |")
    lines.append("|---|---:|---:|---:|")
    for module, tot, tx, pct in rows_all:
        lines.append(f"| {module} | {tot} | {tx} | {pct:.2f}% |")
    lines.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {OUT_MD}")
    print(f"Overall: {grand_translated}/{grand_total} ({overall_pct:.2f}%)")
    print(f"P1: {p1_translated}/{p1_total} ({p1_pct:.2f}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
